apiVersion: v1
kind: Pod
metadata:
  name: golang
spec:
  volumes:
    - name: redis-secret
      secret:
        secretName: redis-secret
  containers:
    - name: golang
      image: golang
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - name: redis-secret
          mountPath: "/etc/paas" # it must be this value
          readOnly: true
      env:
        - name: REDIS_TYPE_READER # Injected  redis variables must have ENV_PREFIX when ENV_PREFIX is not null
          value: "cluster"
        - name: REDIS_HOST_READER
          value: "1.1.1.1 1.1.1.2 1.1.1.3"
        - name: REDIS_PORT_READER
          value: "26379 26379 26379"
        - name: REDIS_DB_NAME_READER
          value: '0'
        - name: REDIS_DB_PASSWORD_READER
          value: "aiyijing"         # redis:passwd
        - name: REDIS_MAX_CONNECTIONS_READER
          value: "32"
        - name: REDIS_KEY_PREFIX_READER
          value: "aiyijing_"
        - name: REDIS_SKIP_FULL_COVER_CHECK_READER
          value: "false"
        - name: REDIS_TIMEOUT_READER
          value: '5'

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  # 目前仅支持toml文件
  redis.toml: `base64`