# normal为单例，cluster为集群
REDIS_TYPE_READER="cluster"

# ip，集群模式下IP会有多个，以逗号分割，IP数量和端口数量一致
REDIS_HOST_READER=["1.1.1.2","1.1.1.3","1.1.1.4"]

# 端口，集群模式下端口会有多个，以逗号分割，IP数量和端口数量一致
REDIS_PORT_READER=["26379","26379","26379"]

# redis的DB name，只有在单例模式下才管用，集群模式会被忽略
REDIS_DB_NAME_READER=0

# 密码,如果没有密码则传空
REDIS_DB_PASSWORD_READER=""

# 最大连接数, 默认为32
REDIS_MAX_CONNECTIONS_READER=32

# redis key的前缀
REDIS_KEY_PREFIX_READER="alauda"

# 当用户屏蔽了CONFIG命令时,需要把这个值改为true，只有集群模式有这个变量
REDIS_SKIP_FULL_COVER_CHECK_READER=false

# redis连接和操作的超时时间为5秒
REDIS_TIMEOUT_READER=5